### ISSUE TITLE
您好，请问这些接口怎么调用

### ISSUE THREAD

**Issue by tomBuddha** [rainzee/WegameApiReversing#1]
您好，请问这些接口怎么调用？请教一下谢谢

**Comment by rainzee** [comment]
在./Examples下，我用Python写了一个小的调用例子。

**Comment by tomBuddha** [comment]
好的 谢谢 ，tgp_id    tgp_ticket 这两个参数怎么获取，谢谢了

**Comment by rainzee** [comment]
登录Wegame后自己通过抓Cookie获取。

**Comment by tomBuddha** [comment]
学习了，收益很多，作者有时间更新一下   battle_details 的例子，坐等更新。
