### ISSUE TITLE
请问有在游戏loading界面获取对面队伍championId的接口么

### ISSUE THREAD

**Issue by sea72** [rainzee/WegameApiReversing#2]
我找了两个
一个是/lol-gameflow/v1/session 但是只能获取本方队伍的
一个是/liveclientdata/activeplayer 但是这个要游戏正式开始才能读到

**Comment by rainzee** [comment]
没有任何办法可以在BP阶段拿到对面的ID，只能在游戏开始之后拿到。

**Comment by sea72** [comment]
不是bp阶段，而是游戏加载阶段，就十个英雄图片那个阶段，summonnerName 和 champion 已经展示出来了，有接口可以读到么

**Comment by sea72** [comment]
游戏开始后你是用哪一个api？

**Comment by rainzee** [comment]
livegamedate
